CREATE TABLE `funciones` (
  `fncod` varchar(255) NOT NULL,
  `fndsc` varchar(45) DEFAULT NULL,
  `fnest` char(3) DEFAULT NULL,
  `fntyp` char(3) DEFAULT NULL,
  PRIMARY KEY (`fncod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `funciones` VALUES ('Controllers/Admin/Admin','Controllers\\Admin\\Admin','ACT','ACT'),('Controllers\\Admin\\Admin','Controllers\\Admin\\Admin','ACT','CTR'),('Controllers\\Mnt\\Autor','Controllers\\Mnt\\Autor','ACT','CTR'),('Controllers\\Mnt\\Autores','Controllers\\Mnt\\Autores','ACT','CTR'),('Controllers\\Mnt\\Autores\\Delete','Controllers\\Mnt\\Autores\\Delete','ACT','CTR'),('Controllers\\Mnt\\Autores\\Edit','Controllers\\Mnt\\Autores\\Edit','ACT','CTR'),('Controllers\\Mnt\\Autores\\New','Controllers\\Mnt\\Autores\\New','ACT','CTR'),('Controllers\\Mnt\\Categorias','Controllers\\Mnt\\Categorias','ACT','CTR'),('Controllers\\Mnt\\Categorias\\Delete','Controllers\\Mnt\\Categorias\\Delete','ACT','CTR'),('Controllers\\Mnt\\Categorias\\Edit','Controllers\\Mnt\\Categorias\\Edit','ACT','CTR'),('Controllers\\Mnt\\Categorias\\New','Controllers\\Mnt\\Categorias\\New','ACT','CTR'),('Controllers\\Mnt\\Funcion_rol','Controllers\\Mnt\\Funcion_rol','ACT','CTR'),('Controllers\\Mnt\\Funciones','Controllers\\Mnt\\Funciones','ACT','CTR'),('Controllers\\Mnt\\Libro','Controllers\\Mnt\\Libro','ACT','CTR'),('Controllers\\Mnt\\Libro\\Delete','Controllers\\Mnt\\Libro\\Delete','ACT','CTR'),('Controllers\\Mnt\\Libro\\Edit','Controllers\\Mnt\\Libro\\Edit','ACT','CTR'),('Controllers\\Mnt\\Libro\\New','Controllers\\Mnt\\Libros\\New','ACT','CTR'),('Controllers\\Mnt\\LibroAutores','Controllers\\Mnt\\LibroAutores','ACT','CTR'),('Controllers\\Mnt\\Libros','Controllers\\Mnt\\Libros','ACT','CTR'),('Controllers\\Mnt\\Libros\\Delete','Controllers\\Mnt\\Libros\\Delete','ACT','CTR'),('Controllers\\Mnt\\Libros\\Edit','Controllers\\Mnt\\Libros\\Edit','ACT','CTR'),('Controllers\\Mnt\\Libros\\New','Controllers\\Mnt\\Libros\\New','ACT','CTR'),('Controllers\\Mnt\\Perfil','Controllers\\Mnt\\Perfil','ACT','CTR'),('Controllers\\Mnt\\Rol','Controllers\\Mnt\\Rol','ACT','CTR'),('Controllers\\Mnt\\Roles','Controllers\\Mnt\\Roles','ACT','CTR'),('Controllers\\Mnt\\Usuario','Controllers\\Mnt\\Usuario','ACT','CTR'),('Controllers\\Mnt\\Usuario\\Del','Controllers\\Mnt\\Usuario\\Del','ACT','CTR'),('Controllers\\Mnt\\Usuario\\Dsp','Controllers\\Mnt\\Usuario\\Dsp','ACT','CTR'),('Controllers\\Mnt\\Usuario\\New','Controllers\\Mnt\\Usuario\\New','ACT','CTR'),('Controllers\\Mnt\\Usuario\\Upd','Controllers\\Mnt\\Usuario\\Upd','ACT','CTR'),('Controllers\\Mnt\\Usuarios','Controllers\\Mnt\\Usuarios','ACT','CTR'),('Controllers\\Mnt\\Usuarios\\Delete','Controllers\\Mnt\\Usuarios\\Delete','ACT','CTR'),('Controllers\\Mnt\\Usuarios\\Edit','Controllers\\Mnt\\Usuarios\\Edit','ACT','CTR'),('Controllers\\Mnt\\Usuarios\\New','Controllers\\Mnt\\Usuarios\\New','ACT','CTR'),('MntUsuarios','MntUsuarios','ACT','CTR');
